services:

  wordpress:
    image: wordpress
    container_name: wp    
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ../plugins/domain-swapper:/var/www/html/wp-content/plugins/domain-swapper      

  db:
    image: mysql:8.0
    container_name: wp_mysql        
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wp_cli:
    image: debian:latest
    container_name: wp_cli    
    command: tail -F anything
    volumes:
      - wordpress:/var/www/html
      - ../plugins/domain-swapper:/var/www/html/wp-content/plugins/domain-swapper                
    
  wpcli:
    depends_on: 
      - db
      - wordpress
    image: wordpress:cli
    container_name: wpcli
    links:
      - db:mysql
    entrypoint: wp
    command: "--info"
    
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb    
    volumes:
      - wordpress:/var/www/html
      - ../plugins/domain-swapper:/var/www/html/wp-content/plugins/domain-swapper            
    working_dir: /var/www/html/wp-content/plugins/domain-swapper 
      
  ha_proxy:
    container_name: ha_proxy    
    image: haproxy:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      - "./certs/:/opt/certs/"      

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
      
volumes:
  wordpress:
  db:
