name: Publish to WordPress.org
on:
  push:
    tags:
     - "*"
jobs:
    tag:
        if: github.repository_owner == 'myridia'
        name: New tag
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build
              run: |
                  cd test/
                  echo "Publish"
            - name: WordPress Plugin Deploy
              uses: 10up/action-wordpress-plugin-deploy@master
              with:
                dry-run: true
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: domain-swapper
                  BUILD_DIR: test/wordpress/wp-content/plugins/domain-swapper/

                  
