name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  deploy:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest

    steps:
      - name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      - name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update
  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: |
              sudo apt-get install -y subversion
   
    
      - name: Checkout
        run: |
              svn --force checkout https://plugins.svn.wordpress.org/domain-swapper wp

      - name: Copy to trunk
        run: |
          rsync -r --exclude=.svn --exclude=.github ./test/wordpress/wp-content/plugins/domain-swapper/ wp/trunk/
          rsync -r --exclude=.svn --exclude=.github ./test/wordpress/wp-content/plugins/domain-swapper/assets/ wp/
          

      - name: SVN add and trunk
        run: |
          cd wp 
          svn add * --force
          svn status
          tag=$(grep "Stable Tag:" ./trunk/readme.txt | cut -d' ' -f3)
          echo $tag >> $GITHUB_ENV
          
          #if svn ls https://plugins.svn.wordpress.org/domain-swapper/tags | grep $tag; then echo found else echo not found fi


          # svn cp trunk tags/$tag
          
      - name: SVN commit  
        run: |
          #svn ci -m 'update' --non-interactive --no-auth-cache --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} 
          echo "end"

        
