name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test/wordpress/wp-content/plugins/domain-swapper
        

    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      with: 
        path: ./test/wordpress/wp-content/plugins/domain-swapper

      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        ASSETS_DIR: assets
        README_NAME: readme.txt
        IGNORE_OTHER_FILES: true
        GITHUB_WORKSPACE: ./test/wordpress/wp-content/plugins/domain-swapper
